### ISSUE TITLE
最近使用一直卡在登录加载界面

### ISSUE THREAD

**Issue by kitmanten** [apifox/apifox#101]
**重现步骤**
打开软件，点击登录会一直加载不进去
![image](https://user-images.githubusercontent.com/41369085/102293439-1117c180-3f82-11eb-8424-478ff70e7bf8.png)

**系统环境**
 - Apifox 版本号：10.26
 - 操作系统：Windows10 1909

**Comment by apifox001** [comment]
麻烦在命令行下运行如下命令，然后把结果发上来，我们看下是否域名解析的问题
ping api.apifox.cn

**Comment by kitmanten** [comment]
![image](https://user-images.githubusercontent.com/41369085/102294968-5ab5db80-3f85-11eb-97de-5fde23402c00.png)

**Comment by apifox001** [comment]
加我微信沟通吧：apifox
