### ISSUE TITLE
为什么我写的Bearer会自动变成Baerar... 我吐了

### ISSUE THREAD

**Issue by wumaorg** [apifox/apifox#108]
**期待的行为**
authoration 写上的Bearer会自动变成 Baerar

**实际表现**
无需多说 看B站链接
[直达](https://www.bilibili.com/video/BV1754y1x7y5/)

**重现步骤**
看以上视频

**系统环境**
 - Apifox 版本号：1.0.26
 - 操作系统：MAC

**Comment by apifox001** [comment]
点开“运行”里的“Header”tab，看看 authoration 填的是什么

**Comment by wumaorg** [comment]
> 点开“运行”里的“Header”tab，看看 authoration 填的是什么

昨晚试了几次  发现又好了 。。。

**Comment by apifox001** [comment]
原因是“修改”tab里修改的参数内容，不会自动同步到“运行”里，这里交互设计上让用户产生了误解，后面我们会优化这个里的交互设计
