### ISSUE TITLE
Mac 上直接无法打开

### ISSUE THREAD

**Issue by chenxiaochun** [apifox/apifox#109]
**期待的行为**

能够正常打开app

**实际表现**

直接提示无法打开app

**系统环境**
 - Apifox 版本号：从官网下载的最新版
 - 操作系统：Mac Catalina 10.15.7

**Comment by apifox001** [comment]
无法打开是点击没反应，还是报什么错？可否加我们微信（微信号：apifox），方便沟通

**Comment by yoqu** [comment]
![image](https://user-images.githubusercontent.com/10415165/103511361-dda1c600-4ea1-11eb-852b-a10c36c5ef9e.png)
mac版本11.1无法正常打开

**Comment by chenxiaochun** [comment]
应该是系统兼容问题：

![image](https://user-images.githubusercontent.com/1744713/103513305-4d658000-4ea5-11eb-99b5-703419dbfe48.png)

**Comment by chenxiaochun** [comment]
@yoqu ，您这个应该就是公司网络权限给限制了

**Comment by apifox001** [comment]
运营小哥上传错文件了，请各位进去官网（ https://www.apifox.cn ）重新下载，感谢

**Comment by chenxiaochun** [comment]
ok
