### ISSUE TITLE
希望有本地部署功能，接受收费，并且最好支持接口历史，所有操作记录

### ISSUE THREAD

**Issue by chengfengfeng** [apifox/apifox#11]

**Comment by apifox001** [comment]
未来会推出私有化部署方案，和离线使用功能

**Comment by taylortaurus** [comment]
> 未来会推出私有化部署方案，和离线使用功能

大概会是什么的样的定价策略。私有化部署收费，那有免费的吗？

**Comment by tobemaster56** [comment]
发展方向和定价策略很重要，能说明一下吗，就像那个蓝湖，一直说自己免费，突然来个收费，让人有点不太爽，我觉得这个一开始，最好就说明白，不是不支持收费，是要尽早说明

**Comment by jnchenfeng** [comment]
> 未来会推出私有化部署方案，和离线使用功能

私有化部署方案有具体的计划吗？

**Comment by apifox001** [comment]
已支持私有化部署，如果有需要请联系微信：apifox
