### ISSUE TITLE
js精度问题，导致返回值在raw和pretty显示的值不一样

### ISSUE THREAD

**Issue by Zhanxueyou** [apifox/apifox#113]
**实际表现**
返回的body里面Raw和Pretty显示的整形数字位数太多导致显示的值不一致
raw是对的，pretty里面显示的是不对的
raw里面的实际值是383870175369379860，但是pretty里面全部显示的是383870175369379840

**重现步骤**
raw显示值：
![image](https://user-images.githubusercontent.com/6895707/103972976-4abaa180-51a9-11eb-9aca-5b9bf6a9443a.png)
pretty显示值：
![image](https://user-images.githubusercontent.com/6895707/103973019-62922580-51a9-11eb-84a4-2b5faf35fb9f.png)

**系统环境**
 - Apifox 版本号：1.1.5
 - 操作系统：win10

**Comment by apifox001** [comment]
最新版已解决
