### ISSUE TITLE
为何智能Mock设置没有生效

### ISSUE THREAD

**Issue by TrendTech** [apifox/apifox#116]
**期待的行为**
我期望的格式是：
 "createdTime": "1987-10-05 20:01:33",

**实际表现**
我生成的时间类mock数据中的格式始终是
 "createdTime": "1987-10-05T20:01:33.829Z",

**重现步骤**
我把关掉内置规则，然后添加自定义规则
![image](https://user-images.githubusercontent.com/48197920/104158670-c2e2ca80-5428-11eb-8d9f-eac1567b5df3.png)
swagger里的定义是这样
![image](https://user-images.githubusercontent.com/48197920/104158684-cfffb980-5428-11eb-956f-13459a9b3954.png)

**系统环境** 
 - Apifox 版本号：刚下的
 - 操作系统：win10

**Comment by apifox001** [comment]
mock 规则优先级问题：
https://www.apifox.cn/help/app/mock/#%E5%9B%9B%E3%80%81mock-%E8%A7%84%E5%88%99%E4%BC%98%E5%85%88%E7%BA%A7


数据字段在自动 Mock 数据时，实际执行的 Mock 规则优先级顺序如下：

1. 接口详情`文档修改`界面返回Response`高级 Mock` 里设置的`期望`（根据接口参数匹配）。
2. 数据结构的字段里设置的`Mock`规则。
3. 数据结构的字段`高级设置`里设置的`最大值`、`最小值`、`枚举值`、`Partten`、`format`。
4. `项目设置`-`智能 Mock 设置`的`自定义规则`。
5. `项目设置`-`智能 Mock 设置`的`内置规则`。
6. 数据结构里字段的`数据类型`。
