### ISSUE TITLE
通过后置操作导出的临时变量，在引用时失败

### ISSUE THREAD

**Issue by DesistDaydream** [apifox/apifox#123]
**期待的行为**
临时变量可以正常使用

**实际表现**
临时变量生成后，在引用时失败

**重现步骤**
在后置操作设置临时变量
![image](https://user-images.githubusercontent.com/39847025/115814648-12716300-a428-11eb-8b87-95c6ee8f643a.png)

变量设置成功
![image](https://user-images.githubusercontent.com/39847025/115814733-36cd3f80-a428-11eb-8617-e4480f9de258.png)

实际请求时，变量并没有生效
![image](https://user-images.githubusercontent.com/39847025/115814680-2026e880-a428-11eb-9ef5-ec5ac0ee90f4.png)

但是如果后置操作是要导出环境变量的话，是可以的。

**系统环境**
 - Apifox 版本号：1.3.2
 - 操作系统：win10

**Comment by apifox001** [comment]
你有的地方是“x_auth_token”，有的地方是“x-auth-token”

**Comment by DesistDaydream** [comment]
第二次截图我好像截错了，第一次截图是没问题的吧？
url 参数那里并没有引入变量的值，依然是 `{{node_ip}}`，显示为 `%7B%7Bnode_ip%7D%7D`，我把第一个环境的测试图重新截取一下~
第一步，获取临时变量
![image](https://user-images.githubusercontent.com/39847025/115822699-8cf5af00-a437-11eb-88fb-76a68a2bf486.png)
第二步，引用临时变量
![image](https://user-images.githubusercontent.com/39847025/115822841-ce865a00-a437-11eb-9504-f5fd97564247.png)
这里可以看到，引用临时变量失败
第三步，测试环境变量
![image](https://user-images.githubusercontent.com/39847025/115822906-ea89fb80-a437-11eb-9dd0-c856127123c6.png)
![image](https://user-images.githubusercontent.com/39847025/115822937-fa094480-a437-11eb-9719-0a92059c1349.png)
这里可以看到，环境变量是没问题的~~

**Comment by apifox001** [comment]
你是在后置操作里“提取变量”，后置操作是在“接口请求”完成后才运行。接口都已经运行结束了，怎么可能还能将提取到的变量放到“请求参数”里呢。

**Comment by DesistDaydream** [comment]
这是两个接口，通过第一个接口获取 IP 地址，保存到临时变量，然后第二个接口使用这个变量获取指定 IP 的信息。

还是说，后置操作的临时变量是没有任何作用的?~

**Comment by apifox001** [comment]
**临时变量** 仅在单次运行（`接口用例`或测试管理里的`测试用例`或`测试套件`）过程中有效，不会持久化保存。

参考这里：https://www.apifox.cn/help/app/api-manage/variables/

**Comment by DesistDaydream** [comment]
原来如此，我对临时变量理解有问题。我以为这个临时变量是缓存到内存中，知道切换项目或关闭程序。

那么，我的这种在接口测试情况，只能用环境变量了么？从我这个情况来看，扩大临时变量的作用范围好像也是不错的选择~~有没可能把这种需求做到开发计划里？~

**Comment by apifox001** [comment]
这种场景用环境变量就好
