### ISSUE TITLE
希望支持模型嵌套字段修改。

### ISSUE THREAD

**Issue by nieaowei** [apifox/apifox#13]
![image](https://user-images.githubusercontent.com/42961884/87224872-68a27780-c3bb-11ea-9553-d829a897b21a.png)
![image](https://user-images.githubusercontent.com/42961884/87224889-81129200-c3bb-11ea-8d0e-6d86b5e75cb4.png)
像这样我其他响应只有data不同而已，但是我依然要手动添加除data外的字段。

**Comment by apifox001** [comment]
最新版已支持高级模式，可以使用“高级模式”->“allOf 多合一”。

最新版已支持 JSON Schema 规范的 allOf、oneOf、anyOf，应该能满足各种模型组合的需求。
JSON Schema 规范参考文档：https://www.apifox.cn/help/reference/json-schema/

**Comment by farzer** [comment]
能否给个实例？
