### ISSUE TITLE
能不能支持导出文档？

### ISSUE THREAD

**Issue by zhangxiaolann** [apifox/apifox#15]
能不能支持导出文档？

**Comment by apifox001** [comment]
【项目设置】-【导入/导出】里可以导出文档，支持导出 OpenApi (原Swagger)、Markdown、Html 等数据格式

**Comment by kaiguoyuanshuai** [comment]
能支持导出YApi 的格式么 现在公司使用YApi,每次在这边写好 还需要复制到那边去

**Comment by apifox001** [comment]
> 能支持导出YApi 的格式么 现在公司使用YApi,每次在这边写好 还需要复制到那边去

试试导出 openApi 格式，然后导入 yapi。
不过建议整个团队都使用 Apifox，这样效率更高。
