### ISSUE TITLE
更改Mock环境不生效

### ISSUE THREAD

**Issue by wtto00** [apifox/apifox#18]
Mock环境管理设置中，我修改了前置URL，  
可是访问的时候，仍然是只有修改前默认的前置URL才有效返回200，  
访问修改后的前置URL地址，返回404，不存在接口。  

具体可看截图：
![image](https://user-images.githubusercontent.com/30424139/87760637-9f0c4680-c842-11ea-866d-e5f4adf9eb0a.png)
> 我添加了后缀`/api`

![image](https://user-images.githubusercontent.com/30424139/87760772-d975e380-c842-11ea-8091-92a5b24a5dc9.png)
> 访问修改后的前置URL地址返回404错误

![image](https://user-images.githubusercontent.com/30424139/87760823-f1e5fe00-c842-11ea-9354-3adaa88a989b.png)
> 访问修改前的前置URL，则成功返回200

我试过重启软件，却没有任何改变

**Comment by apifox001** [comment]
Mock 的前置 URL 是固定的，不能修改。参考这里：https://www.apifox.cn/help/app/mock/#%E4%BA%8C%E3%80%81mock-%E8%AF%B7%E6%B1%82-url


环境里的【Mock Server】只是一个普通的环境，只是为了方便使用，创建项目的时候系统自动生成了一个名为【Mock Server】的环境。

**Comment by wtto00** [comment]
@apifox001 那么这里的修改操作只是作为文档的显示作用，和mock Server没有任何关系的。那这里能不能改个名字？

事实上默认生成的mock Server被我删了，这个是我自己建的同名的而已。
