### ISSUE TITLE
respose数据结构校验失败

### ISSUE THREAD

**Issue by juallyH** [apifox/apifox#21]
期望返回的字段是string 类型，当返回的是 null 时 校验不通过。期望可以校验通过

**Comment by apifox001** [comment]
nullable 选项真正开发中，预计下周可以完成，建议加我们的微信群或者QQ群，到时候会先在群里发布，等稳定后会全量发布

**Comment by apifox001** [comment]
最新正式版已发布，已支持设置“允许NULL”，已解决该问题，请更新版本
