### ISSUE TITLE
mock server 不允许PATCH方法？

### ISSUE THREAD

**Issue by jp3049** [apifox/apifox#31]
PATCH方法的接口全都返回了Status: 405 Method Not Allowed

**Comment by apifox001** [comment]
下个版本就会支持

**Comment by apifox001** [comment]
最新 alpha 版已支持，可以加官网 微信群 或 QQ群，参与 alpha 版内测。
加群方式：https://www.apifox.cn/help/app/contact-us/

*注意*：
1、Apifox 新功能都会先在 alpha 版上线，等稳定后才会合到正式版。
2、alpha版可能会有一些bug，如遇到问题及时在群里反馈，我们会第一时间解决。
3、alpha 版和正式版数据是互通的。
4、已经是 alpha 版的，直接点击软件内更新（或者等待1小时候自动更新）。

**Comment by jp3049** [comment]
感谢！
