### ISSUE TITLE
请求rest接口请求头中Content-Type传了不生效

### ISSUE THREAD

**Issue by Wangxy013** [apifox/apifox#37]
使用postman工具相同传参调用正常，使用apifox调用接口提示415，后端接口要求Content-Type必传application/json，疑似apifox传了没生效
![image](https://user-images.githubusercontent.com/40142651/90228476-df161780-de48-11ea-9060-6e459e41e3f2.png)

**Comment by apifox001** [comment]
GET 请求设置 Content-Type 问题，最新 alpha 版已解决。
加官方微信群、QQ 群或钉钉群，参与 alpha 版内测。
加群方式：apifox.cn/help/app/contact-us

注意：
1、Apifox 新功能都会先在 alpha 版上线，等稳定后才会合到正式版。
2、alpha版可能会有一些bug，如遇到问题及时在群里反馈，我们会第一时间解决。
3、alpha 版和正式版数据是互通的。
4、已经是 alpha 版的，直接点击软件内更新（或者等待1小时候自动更新）。

**Comment by apifox001** [comment]
最新正式版已发布，已解决该问题，请更新版本
