### ISSUE TITLE
返回 response 不能粘贴

### ISSUE THREAD

**Issue by kdming** [apifox/apifox#43]
**期待的行为**
接口修改功能，返回response结构可以直接粘贴json数据

**实际表现**
点击json智能识别/快捷导入后，弹窗的编辑框无法直接粘贴json

**系统环境**
 - Apifox 版本号：1.0.14
 - 操作系统：macOs 10.14.6

**Comment by kdming** [comment]
如果返回数据字段很多的情况下，一个个的慢慢写，真的很影响效率

**Comment by apifox001** [comment]
这边测试，无法复现，加我微信沟通吧（微信号：apifox）
