### ISSUE TITLE
[問題回報] 請求回應的 Cookie encodeURi、decodeURI 機制與 Postman 不一致，造成 egg-session 失效問題。

### ISSUE THREAD

**Issue by trylovetom** [apifox/apifox#5]
### 描述

我使用 eggjs 作為我的後端服務器，eggjs 使用 base64 的格式在 cookie 中儲存使用者的 session。
因為 base64 有 `=` 這個符號，當我在請求的回應時設定使用者的 session，apifox 取得 cookie 後沒有 decodeURI，造成下請求時，認不得此 seesion，這問題在 postman 與 chrome 中是不存在的。

### 預期結果
**postman 回應 set-cookie**
session 結尾的 `=` 為 `%3d`
<img width="802" alt="截圖 2020-07-03 下午7 42 10" src="https://user-images.githubusercontent.com/13268073/86466214-d28ca280-bd65-11ea-9669-b024f7114e23.png">

**postman cookie**
session 結尾的`%3d` 被解析為 `=`
<img width="753" alt="截圖 2020-07-03 下午7 42 40" src="https://user-images.githubusercontent.com/13268073/86466315-f819ac00-bd65-11ea-8b7f-874fc6580d33.png">

**postman 請求 cookie**
帶出去的 session 結尾為 `=` 而不是 `%3d`

### 實際解果
**apifox 回應 set-cookie**
session 結尾為 `=` 而不是 `%3d`
<img width="1159" alt="截圖 2020-07-03 下午7 48 02" src="https://user-images.githubusercontent.com/13268073/86467079-58f5b400-bd67-11ea-8dc4-42923f124e37.png">

**apifox cookie**
`%3d` 未被解析為 `=`
<img width="1043" alt="截圖 2020-07-03 下午7 48 08" src="https://user-images.githubusercontent.com/13268073/86467025-395e8b80-bd67-11ea-9ebf-9c0a17b538a4.png">

**apifox 請求 cookie**
帶出去的 session 結尾為 `%3d` 而不是 `=`

**Comment by apifox001** [comment]
已解决，[从官网下载最新版](https://www.apifox.cn/)即可

**Comment by trylovetom** [comment]
太棒了！已確認解決。
