### ISSUE TITLE
代理配置: Proxy configure

### ISSUE THREAD

**Issue by lihe6666** [apifox/apifox#62]
**希望增加的功能/特性**
简要描述你希望增加的功能

_### 我个人觉得可以加一个代理的功能啊_
**使用场景**
说明为什么你需要这个功能，使用场景是什么样的

_### 抓包啊，分析http/https/websocks_

**详细详细**
功能/特性需求点的详细说明

_### 比如我的接口就在本地。简单的hosts 不能完全解决问题，那可能会使用一些 类似于代理抓包的工具，如：whistle，这个工具需要先请求接口到8899 或者其它端口，然后捕获包_

**Comment by lihe6666** [comment]
即使没有这个功能，系统也可以设置全局代理。但是有了这个功能的话，会更完美，并且本机与apifox 的访问互不干扰

**Comment by apifox001** [comment]
后续会增加代理设置功能

**Comment by lihe6666** [comment]
好的，希望这个好产品慢慢盛行起来！
