### ISSUE TITLE
发送接口请求后，预执行脚本可以正常保存

### ISSUE THREAD

**Issue by Zhanxueyou** [apifox/apifox#67]
**期待的行为**
发送接口请求后，预执行脚本可以正常保存

**实际表现**
执行时写入了预执行脚本，请求接口之后关闭接口，再次打开，预执行脚本内容被清空了，没有正常保存

**系统环境**
 - Apifox 版本号：1.0.24
 - 操作系统：win10

**Comment by apifox001** [comment]
请点击“保存为用例”按钮
