### ISSUE TITLE
退出软件后，后台进程驻留

### ISSUE THREAD

**Issue by terrypluto** [apifox/apifox#76]
打开apifox
![image](https://github.com/apifox/apifox/assets/134566055/e618e6e4-2170-49e6-a460-d7475911f61f)
关闭apifox
![image (1)](https://github.com/apifox/apifox/assets/134566055/bdbee87c-e013-4a40-bbed-dc05d9fbb588)
只能通过`结束任务`关闭，不然一直再后台驻留

**Comment by terrypluto** [comment]
这个居然需要手动在windows开启自启关闭。

**Comment by terrypluto** [comment]
只要重新启动apifox又会给我重新给加到启动项里，而且还是会驻留，直接删除ApifoxAppAgent.exe程序，下次启动会重新给你下载。最新解决方案：右键ApifoxAppAgent.exe ->属性->安全->：逐一编辑每个用户，拒绝所有的权限

**Comment by terrypluto** [comment]
这种后台程序，apifox不搞一个设置，还偷偷来这一手，在官方文档就顺便一提就算了，还不能完全解决。谁知道你这个干啥的，看到后缀是agent的程序，就让我想起了公司装的监控软件

**Comment by SunCoya** [comment]
删掉软件还能重新启动，豪鹅新啊

**Comment by SunCoya** [comment]
删掉软件之后这个进程还会开机自启
C:\Users\用户名\AppData\Roaming里面可删掉apifox的这个文件夹（先停止任务）

**Comment by DawnLou** [comment]
太腻味这个后台进程，我已经把ApiFox卸载了

**Comment by bbuugg** [comment]
> 只要重新启动apifox又会给我重新给加到启动项里，而且还是会驻留，直接删除ApifoxAppAgent.exe程序，下次启动会重新给你下载。最新解决方案：右键ApifoxAppAgent.exe ->属性->安全->：逐一编辑每个用户，拒绝所有的权限

尝试了修改权限、删除这个exe，启动后还会运行，而且文件也恢复了。
