### ISSUE TITLE
企业环境或者商业环境中使用是否收费

### ISSUE THREAD

**Issue by yb138111** [apifox/apifox#77]
在企业环境内或者商业环境中使用是否收费？
还是说基础版对于企业和个人一样是免费的？

**Comment by apifox001** [comment]
基础版对于企业和个人一样都是免费的
目前只有私有化部署版本是收费的

**Comment by aogg** [comment]
可以弄个私有化同步吧，这样可以私有团队使用

不知道是否和你们营收理念冲突
