### ISSUE TITLE
response和response示例

### ISSUE THREAD

**Issue by xuweijie4030** [apifox/apifox#79]
response示例
   response希望可以直接从运行结果中导入？
response
   response希望可以直接从response示例中导出字段
参数说明
   希望可以记录添加过的字段说明，添加相同或类型的字段时可以直接选择

**Comment by apifox001** [comment]
1、response示例：最新版，运行结果，鼠标移到的右上角 “...”，可以“添加到 Response 示例”
2、response：建议复制返回的数据，然后去“修改文档”，然后用“json/xml 智能识别/快捷导入”
