### ISSUE TITLE
APIFOX CLI 無法使用導出數據

### ISSUE THREAD

**Issue by Fashaun** [apifox/apifox#84]
**期待的行为**
導出數據 apifox 格式數據可以直接透過 apifox cli 做使用

**实际表现**
無法使用 
Error Message : error: Cannot read property 'forEach' of undefined

**重现步骤**
清晰描述重现步骤，最好搭配截图

**系统环境**
 - Apifox 版本号：1.0.26
 - 操作系统：debian linux
 - nodejs version : v14.15.1

![image](https://user-images.githubusercontent.com/5792071/100341422-82192880-3017-11eb-8a09-037c76494df6.png)

**Comment by apifox001** [comment]
Apifox Cli 在 Apifox 的【测试用例】和【测试套件】导出Apifox CLI格式数据。【项目设置】里导出的项目数据是不能直接运行的。参考文档：https://www.apifox.cn/help/cli/
