### ISSUE TITLE
已登录的帐户已经会失效

### ISSUE THREAD

**Issue by thtznet** [apifox/apifox#90]
**期待的行为**
已登录帐户不要经常无故登出

**实际表现**
已登录的帐户经常会无故登出，需要重新登录：新建了一个接口，填了一堆数据后点【保存】时跳转到登录页面，但是在新建接口的时候帐户是登录状态的。

**重现步骤**
无

**系统环境**
 - Apifox 版本号：1.0.26
 - 操作系统：Windows 10 1903

**Comment by apifox001** [comment]
该问题现在是否已经解决？如果还存在，请加我微信（微信号：apifox）
