### ISSUE TITLE
能不能给一个适配Mac Big Sur版本的图标

### ISSUE THREAD

**Issue by azhu003** [apifox/apifox#91]
**希望增加的功能/特性**
强迫症受不了 哈哈哈哈

**使用场景**
![image](https://user-images.githubusercontent.com/29949867/101141451-4867a380-364f-11eb-9a13-5e38c30f43d2.png)

**详细详细**
在[这里](https://macosicons.com/)也没有找到合适的图标可以替代

**Comment by apifox001** [comment]
请下载最新版 Apifox，已更新图标
